name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/2 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: blackchoey/stale@releases/v1.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-issue-label: 'no-issue-activity'
        days-before-stale: 0
        only-labels: 'dependency'
        last-updated-user-type: 'collaborator'
